"""
Inverted Pendulum on a Cart - symbolic derivation, linearization, LQR controller,
nonlinear simulation and plotting.

How to use:
 - Run this file in a Python environment with: numpy, scipy, sympy, matplotlib
 - It computes the nonlinear dynamics, linearizes about the upright position,
   synthesizes an LQR controller, and simulates the closed-loop nonlinear system.
 - At the bottom you can toggle `do_animation = True` to see a simple matplotlib animation.

Author: Generated by ChatGPT (GPT-5 Thinking mini)
"""

import numpy as np
from scipy.integrate import solve_ivp
from scipy import linalg
import matplotlib.pyplot as plt
import sympy as sp

# -------------------------
# Parameters (SI units)
# -------------------------
M = 0.5      # mass of the cart (kg)
m = 0.2      # mass of the pendulum (kg)
ell = 0.3    # length to pendulum center of mass (m)
g = 9.81     # gravity (m/s^2)

# optional viscous friction on cart
b = 0.0

# -------------------------
# Symbolic derivation (nonlinear equations)
# -------------------------
# Coordinates: x (cart pos), theta (pendulum angle, 0 = upright)
x_s, th_s, xdot_s, thdot_s, F_s = sp.symbols('x th xdot thdot F', real=True)

# generalized coordinates and derivatives
q = sp.Matrix([x_s, th_s])
qdot = sp.Matrix([xdot_s, thdot_s])

# Define useful expressions
sin = sp.sin
cos = sp.cos

# Kinetic energy T and potential energy V (Lagrange)
# Cart KE
T_cart = sp.Rational(1,2)*M*xdot_s**2
# Pendulum COM velocity (assuming massless rod with point mass at distance ell)
# x_com = x + ell * sin(th)
x_com = x_s + ell * sin(th_s)
# y_com = ell * cos(th)
y_com = ell * cos(th_s)
# velocities
x_com_dot = sp.diff(x_com, x_s)*xdot_s + sp.diff(x_com, th_s)*thdot_s
y_com_dot = sp.diff(y_com, x_s)*xdot_s + sp.diff(y_com, th_s)*thdot_s
T_pend = sp.Rational(1,2)*m*(x_com_dot**2 + y_com_dot**2)
T = sp.simplify(T_cart + T_pend)
V = m*g*y_com

# Lagrangian
L = T - V

# Generalized forces: force F acts in x-direction on cart
Q = sp.Matrix([F_s - b*xdot_s, 0])

# Lagrange's equations: d/dt(dL/dqdot) - dL/dq = Q
dL_dq = sp.Matrix([sp.diff(L, q_i) for q_i in q])
dL_dqdot = sp.Matrix([sp.diff(L, qdot_i) for qdot_i in qdot])

d_dt_dL_dqdot = sp.Matrix([sp.diff(dL_dqdot_i, x_s)*xdot_s + sp.diff(dL_dqdot_i, th_s)*thdot_s + sp.diff(dL_dqdot_i, xdot_s)*0 + sp.diff(dL_dqdot_i, thdot_s)*0
                             for dL_dqdot_i in dL_dqdot])
# Here we did partial time-derivative symbolically treating xdot_s and thdot_s as independent; it's sufficient for deriving

# Equations of motion (symbolic)
EOM = sp.simplify(d_dt_dL_dqdot - dL_dq - Q)

# Solve for accelerations xdd and thdd using sympy (expressions in terms of x,th,xd,thd,F)
xdd_s, thdd_s = sp.symbols('xdd thdd')
unknowns = [xdd_s, thdd_s]

# Build the algebraic system by expressing second derivatives
# Using manual formulation (derived from standard manipulations) is more robust than time derivative substitution above
# We'll instead build the well-known equations directly for clarity:
# (M + m) * x_dd + m*ell*cos(th)*th_dd - m*ell*sin(th)*th_dot^2 = F - b*xdot
# m*ell*cos(th)*x_dd + m*ell^2*th_dd - m*g*ell*sin(th) = 0

eq1 = (M + m)*xdd_s + m*ell*sp.cos(th_s)*thdd_s - m*ell*sp.sin(th_s)*thdot_s**2 - (F_s - b*xdot_s)
eq = None
# sympy quirk: don't compare; use eq form

A11 = (M + m)
A12 = m*ell*sp.cos(th_s)
A21 = m*ell*sp.cos(th_s)
A22 = m*ell**2

B1 = F_s - b*xdot_s + m*ell*sp.sin(th_s)*thdot_s**2
B2 = m*g*ell*sp.sin(th_s)

# Solve linear system A * [xdd; thdd] = [B1; B2]
A = sp.Matrix([[A11, A12],[A21, A22]])
B = sp.Matrix([B1, B2])
sol = sp.simplify(A.LUsolve(B))

xdd_expr = sp.simplify(sol[0])
thdd_expr = sp.simplify(sol[1])

# Lambdify for numeric evaluation
xdd_fun = sp.lambdify((x_s, th_s, xdot_s, thdot_s, F_s), xdd_expr, 'numpy')
thdd_fun = sp.lambdify((x_s, th_s, xdot_s, thdot_s, F_s), thdd_expr, 'numpy')

# -------------------------
# State-space (nonlinear) : state vector [x, xdot, theta, thetadot]
# -------------------------
def dynamics_nonlinear(t, state, controller=None):
    x, xdot, th, thdot = state
    # controller returns force given state and time
    F = 0.0 if controller is None else controller(t, state)
    xdd = xdd_fun(x, th, xdot, thdot, F)
    thdd = thdd_fun(x, th, xdot, thdot, F)
    return [xdot, float(xdd), thdot, float(thdd)]

# -------------------------
# Linearization about upright (th=0)
# State: [x, xdot, th, thdot]
# Small-angle linearization yields standard A,B matrices
# We'll compute them symbolically from the nonlinear expressions
# -------------------------
# Define symbols for linearization (use same names)
x_sym, th_sym, xd_sym, td_sym, F_sym = sp.symbols('x_sym th_sym xd_sym td_sym F_sym')

xdd_sym = sp.Matrix([xdd_expr.subs({x_s:x_sym, th_s:th_sym, xdot_s:xd_sym, thdot_s:td_sym, F_s:F_sym})])
thdd_sym = sp.Matrix([thdd_expr.subs({x_s:x_sym, th_s:th_sym, xdot_s:xd_sym, thdot_s:td_sym, F_s:F_sym})])

f_sym = sp.Matrix([xd_sym, xdd_sym[0], td_sym, thdd_sym[0]])

state_sym = sp.Matrix([x_sym, xd_sym, th_sym, td_sym])

# Jacobians
A_sym = sp.simplify(sp.Matrix([[sp.diff(fi, sj) for sj in state_sym] for fi in f_sym]))
B_sym = sp.simplify(sp.Matrix([[sp.diff(fi, F_sym)] for fi in f_sym]))

# Evaluate at upright equilibrium: th=0, xd=0, td=0
subs_eq = {th_sym:0, xd_sym:0, td_sym:0, x_sym:0}
A_num = np.array(A_sym.subs(subs_eq).subs(F_sym,0).evalf(), dtype=float)
B_num = np.array(B_sym.subs(subs_eq).subs(F_sym,0).evalf(), dtype=float)

# tidy small values
A_num[np.abs(A_num) < 1e-12] = 0.0
B_num[np.abs(B_num) < 1e-12] = 0.0

# Print linearized matrices (user can inspect)
print('A matrix (linearized):')
print(A_num)
print('\nB matrix (linearized):')
print(B_num)

# -------------------------
# LQR controller design
# -------------------------
# We design continuous-time LQR: minimize integral(x' Q x + u' R u) dt
Q = np.diag([10.0, 1.0, 100.0, 1.0])   # penalize theta heavily
R = np.array([[0.001]])                # small control penalty (aggressive)

# Solve Riccati
P = linalg.solve_continuous_are(A_num, B_num, Q, R)
K = np.dot(np.linalg.inv(R), B_num.T.dot(P))

print('\nLQR gain K:')
print(K)

# Controller (state feedback) — keep reference at zero
def lqr_controller_from_K(K):
    def ctrl(t, state):
        x, xdot, th, thdot = state
        s = np.array([x, xdot, th, thdot])
        u = -K.dot(s)
        return float(u)
    return ctrl

controller = lqr_controller_from_K(K)

# -------------------------
# Simulation of nonlinear closed-loop
# -------------------------
# initial condition: small tilt + some cart displacement
x0 = 0.0
xd0 = 0.0
th0 = 0.2    # 0.2 rad ~ 11.5 degrees
thd0 = 0.0
state0 = [x0, xd0, th0, thd0]

t_span = (0.0, 8.0)
t_eval = np.linspace(t_span[0], t_span[1], 2001)

sol_cl = solve_ivp(lambda t, y: dynamics_nonlinear(t, y, controller), t_span, state0, t_eval=t_eval, rtol=1e-6, atol=1e-8)

# -------------------------
# Plot results
# -------------------------
fig, axes = plt.subplots(3,1, figsize=(8,8), sharex=True)
axes[0].plot(sol_cl.t, sol_cl.y[0], label='x (m)')
axes[0].legend()
axes[1].plot(sol_cl.t, sol_cl.y[2], label='theta (rad)')
axes[1].axhline(0, color='k', linewidth=0.5)
axes[1].legend()
axes[2].plot(sol_cl.t, -K.dot(sol_cl.y).T, label='u (N)')
axes[2].legend()
axes[2].set_xlabel('time (s)')
plt.tight_layout()
plt.show()

# -------------------------
# Optional: simulate open-loop for comparison
# -------------------------
sol_ol = solve_ivp(lambda t, y: dynamics_nonlinear(t, y, None), t_span, state0, t_eval=t_eval)

plt.figure(figsize=(6,3))
plt.plot(sol_ol.t, sol_ol.y[2], label='open-loop theta (rad)')
plt.plot(sol_cl.t, sol_cl.y[2], label='closed-loop theta (rad)')
plt.legend(); plt.xlabel('time (s)'); plt.title('Open-loop vs Closed-loop')
plt.show()

# -------------------------
# Simple animation (cart + pendulum)
# -------------------------
import matplotlib.animation as animation

do_animation = False
if do_animation:
    fig2, ax2 = plt.subplots(figsize=(6,3))
    ax2.set_xlim(-1.0, 1.0)
    ax2.set_ylim(-0.2, 0.8)
    cart_width = 0.3
    cart_height = 0.15
    line, = ax2.plot([], [], lw=2)
    rect = plt.Rectangle((0,0), cart_width, cart_height, fc='tab:blue')
    ax2.add_patch(rect)
    pend_line, = ax2.plot([], [], lw=2)

    def init_anim():
        rect.set_xy((-cart_width/2, 0))
        pend_line.set_data([], [])
        return rect, pend_line

    def animate(i):
        x = sol_cl.y[0, i]
        th = sol_cl.y[2, i]
        rect.set_xy((x - cart_width/2, 0))
        pend_x = x + ell * np.sin(th)
        pend_y = cart_height + ell * np.cos(th)
        pend_line.set_data([x, pend_x], [cart_height, pend_y])
        return rect, pend_line

    ani = animation.FuncAnimation(fig2, animate, frames=len(sol_cl.t), init_func=init_anim, interval=10, blit=True)
    plt.show()

# -------------------------
# Save K and linearization for user's reference
# -------------------------
linearization = {'A': A_num, 'B': B_num, 'K': K}

print("\nDone. You can modify parameters, Q/R, initial conditions, or switch to a PID controller if you prefer.")
